apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-tracker
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: budget-tracker
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"