apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: budget-tracker-dev
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dev
