apiVersion: v1
kind: Service
metadata:
  name: budget-tracker
  namespace: budget-tracker
spec:
  selector:
    app: budget-tracker
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
  