apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: weather-api-token
  namespace: default
spec:
  encryptedData:
    WEATHER_API_KEY: AgBn3uRAbl6ljEoHFwxHX5t3pZgsG80K3TV6sJe0fZR1e3Flv5ZVuA8t5yBhaw4MnUa+JEMSK7MP/9jV+Yue+UBKbg5RliQ76G+6lKIm8mc/wN3tPfaXZUI4+kBf2havw/Nxive4Fpwa1tV85KjSyb/CSQIlxQE9gwoYoEIZPwHiMp2wMA6d0fElmEEVbt5KRPfomPRQfotICSjIEujVFd0h6KCegdkpCYDZCUwiQt602RTrCT1K6cPMuoV0nKxbvWXWhIQDW+PD1Eu5ZkY2Yx3MAjXrtZk7IkOBQkWYTRtCkjuCeD1NUHvbMwAbkqDeHwy9jEVJ3rK1O3PeJoH0CCts2j8Lp793CadDRye8tvrj27MbJaNi6n9TH/3aUhfPfm1DePXChZlnhFl7JleezL25lpbLoc7WfLOjm9A4r+SxeQx1sPqzg/VJyNMhnD/MSKC+lOU8sEnO9PIp7WlpQHpTgLUVFPbMZY81n7BcMcFpdH+ERr1qrQ1eYQBYecLMMRXB3feKJyGlMbF8K9WIA6RST6ofucmV9MUL1gbZzRJu/x8khe8RJmfBbc3+cgZd8kmfZz6e9ZD7yBeRSbFd2M2nmNcwKRxQuPeDpKMzVz7f/mLgXpKKlYmwA2PQdS5Vo5588Fi9gNlVHQTtWXUeTVEtWbNIUEm9/NVr4+GMQN+Y1enkAQNo10NxEQIPVpqF1/6Nhw08xDGGlZUktOueYWETAs5YwZIlEHzqAqz5SA+Z
  template:
    metadata:
      name: weather-api-token
      namespace: default
    type: Opaque