apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: weather-api-token
  namespace: budget-tracker
spec:
  encryptedData:
    WEATHER_API_KEY: AgCPgbWFTFMzU39Ol8G0Wrp2JfQn0lM62xwbzwuov1PuKxDxNEZlo6PEuNzaTJ0YFyHZJ5q+YQziBqAtn2oDGh/B+au4SF54yPrZhKmEhq7TZ/j+1iPLd+p/lvsZbJL0exe6FvthlTmhb7NgWwyYU5d+qxA377c1k4TFfNh8DLV5bUnYa0qDefzQMv/7jmvSSNGUosREIpuTtAq5TZsqMdNrPAlp2UZm86I29lIXzJkBLIOcjGQ+U+IFjATeLUYAbTSIeJFVjVCavn3V8uYLQqxsqsCR5pwP+v9Qoy4wD2dfld/xLfQYtpEu1e60Js04PLLtU8JRwyCz6+4nkBoZv9HoZijJCaDrrygPy5VQ15azMnVk+99qnu4NyP2BX0xzwYFGrSO1zoTzla6FlHrBPDj6qJTvHkQXlvw9PiIrTp+FU2htUfI4EwRZdfXeRdUwVBXkBN+DLtDZezluECcZe8lVXpr8fYoS+bPkP7wpteiGaQBa3pHg/PuX+LyM4x6fLTUZMWvyLl8RFw60IPoCDFDR3oiVblzsizHtI7PVK7iX++irYkN3LfQgakxb7/xwwlFUg8x66XrExKSV4MWyJjZanyYdy4Yh87Tg2cH2HfGSQSnF7mTgv/mYOXoOYLX6EGYsHkcDP66EF2RJj9uHfLPBIYPu5GtZRatWrZb8qAQTd9cIBovP6PP1hOOJN3KaIUkwIgxg/2DshhXD9ZVAadUSDDRlGBV7el9Ye/YjMPbH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: weather-api-token
      namespace: budget-tracker
    type: Opaque