apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-tracker
  namespace: budget-tracker
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: budget-tracker
          image: ghcr.io/spodoy/budgettracker:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"